version: "3.8"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app
      - ./backend/wizard.db:/app/wizard.db
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./wizard.db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
